version: '3.9'
services:
  db:
    image: postgres:15.2
    environment:
      POSTGRES_USER: spotitube
      POSTGRES_PASSWORD: spotitube
    volumes:
      - './db/:/docker-entrypoint-initdb.d/:ro'
    ports:
      - '5432:5432'
  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    environment:
      # JAVA_TOOL_OPTIONS: -javaagent:lib/jacocoagent.jar=output=tcpserver,address=* -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - '8080:8080'
      - '8443:8443'
      - '6300:6300'
      - '5005:5005'
