name: CI
on: push
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: check jacocoTestCoverageVerification --parallel
      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: test-reports
          path: |
            app/*/build/test-results/*/TEST-*.xml
            app/*/build/reports/jacoco/test/jacocoTestReport.xml
